=== eXplosive57/Contributo-3-Kerrouche.XML-DOM/Progetto/catalogo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="catalogo">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="smartphone" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="smartphone">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="nome" />
        <xsd:element ref="marca"/>
        <xsd:element ref="prezzo"/>
        <xsd:element ref="batteria"/>
        <xsd:element ref="descrizione" />
        <xsd:element ref="img"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>


  <xsd:element name="nome" type="string" />
  <xsd:element name="marca" type="string"/>
  <xsd:element name="prezzo" type="xsd:integer"/>
  <xsd:element name="batteria" type="string"/>
  <xsd:element name="descrizione" type="string"/>
  <xsd:element name="img" type="string"/>

</xsd:schema>

=== eXplosive57/Contributo-3-Kerrouche.XML-DOM/Progetto/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalogo.xsd">
  <smartphone>
    <nome>iPhone 11</nome>
    <marca>Apple</marca>
    <prezzo>550</prezzo>
    <batteria>4000</batteria>
    <descrizione>Il telefono ha uno schermo OLED Super Retina XDR da 6,1 pollici per l'iPhone 14 e 6,7 pollici per l'iPhone 14 Plus, con un formato di 19,5:9.È dotato di un vetro "Ceramic Shield", un rivestimento di cristalli di ceramica introdotto per la prima volta sulla linea iPhone 12.È dotato del chip Apple A15 Bionic, connettività 5G, la cui tecnologia a onde millimetriche mmWave è disponibile solo in alcuni mercati.Gli iPhone 14 ripropongono lo stesso design del modello precedente.</descrizione>
    <img>foto/iphone11.avif </img>
  </smartphone>
  <smartphone>
    <nome>iPhone 12</nome>
    <marca>Apple</marca>
    <prezzo>690</prezzo>
    <batteria>4500</batteria>
    <descrizione>L'iPhone 12 offre un design elegante ecompatto con un display Super Retina XDR per colori vividi.Il chip A14 Bionic garantisce prestazioni veloci e un'efficienza energetica ottimizzata.La fotocamera a doppia lente cattura foto di alta qualità, e la modalità Notte migliora le prestazioni in condizioni di scarsa luminosità.La compatibilità con la rete 5G offre una connettività veloce e affidabile.</descrizione>
    <img>foto/iphone12.avif </img>
  </smartphone>
  <smartphone>
    <nome>iPhone 13</nome>
    <marca>Apple</marca>
    <prezzo>799</prezzo>
    <batteria>5000</batteria>
    <descrizione>L'iPhone 13 offre un display Super Retina XDR per colori vividi e contrasto elevato.Il potente chip A15 Bionic garantisce prestazioni veloci e un'efficienza energetica ottimizzata.La fotocamera a doppia lente con modalità Notte permette di scattare foto di alta qualità anche in condizioni di scarsa illuminazione.La durata della batteria è migliorata e l'iPhone 13 è resistente all'acqua e alla polvere.</descrizione>
    <img>foto/iphone13.avif </img>
  </smartphone>
</catalogo>
